spring:
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #  show_sql: true
        format_sql: true
        use_sql_comments: true # sql 과 함께 jpql 주석처리되어  콘솔창에 출력
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always